name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        # 直接安装 flet，不再寻找 requirements.txt 防止报错
        pip install flet

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'
        channel: 'stable'

    - name: Flet Build APK
      run: |
        flet build apk --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/apk/app-release.apk
